### ISSUE TITLE
TypeError: unsupported operand type(s) for *: `dict` and `dict` in MALA.py after flowMC-v3.0.0 release

### ISSUE THREAD

**Issue by Qazalbash** [kazewong/flowMC#162]
# Description
I'm working through the [flowMC tutorial on running flowMC](https://flowmc.readthedocs.io/en/main/tutorials/dualmoon/). Previously, I passed the data as a dictionary to the sampler, and it worked well until the `flowMC-v3.0.0` release. I'm encountering an error involving a multiplication operation between two dictionaries, which doesn't seem right. I'll attach both the error message and the code needed to replicate it.

## Error
```bash
❰gradf❙~/Desktop/error❱✔≻ python reproduce.py                                                                                                        (gwkenv)
['n_dim', 'n_chains', 'n_local_steps', 'n_global_steps', 'n_loop', 'output_thinning', 'verbose']
Global Tuning:   0%|                                                                                                                  | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/gradf/Desktop/error/reproduce.py", line 87, in <module>
    nf_sampler.sample(initial_position, data=data)
  File "/home/gradf/miniforge3/envs/gwkenv/lib/python3.11/site-packages/flowMC/Sampler.py", line 196, in sample
    ) = strategy(
        ^^^^^^^^^
  File "/home/gradf/miniforge3/envs/gwkenv/lib/python3.11/site-packages/flowMC/strategy/global_tuning.py", line 90, in __call__
    ) = local_sampler.sample(
        ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gradf/miniforge3/envs/gwkenv/lib/python3.11/site-packages/flowMC/proposal/MALA.py", line 159, in sample
    state = self.update_vmap(i, state)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gradf/miniforge3/envs/gwkenv/lib/python3.11/site-packages/flowMC/proposal/MALA.py", line 121, in update
    new_position, new_log_p, do_accept = self.kernel(
                                         ^^^^^^^^^^^^
  File "/home/gradf/miniforge3/envs/gwkenv/lib/python3.11/site-packages/flowMC/proposal/MALA.py", line 78, in kernel
    dt2 = dt * dt
          ~~~^~~~
TypeError: unsupported operand type(s) for *: 'dict' and 'dict'
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
```

## Code

```python
import jax
from flowMC.nfmodel.rqSpline import MaskedCouplingRQSpline
from flowMC.proposal.MALA import MALA
from flowMC.Sampler import Sampler
from jax import numpy as jnp
from jax import random as jrd
from numpyro import distributions as dist

data = {
    "data": {
        0: jrd.truncated_normal(jrd.PRNGKey(0), lower=0.0, upper=0.5, shape=(1000,)),
        1: jrd.truncated_normal(jrd.PRNGKey(1), lower=0.0, upper=0.5, shape=(1500,)),
        2: jrd.truncated_normal(jrd.PRNGKey(2), lower=0.0, upper=0.5, shape=(2000,)),
    }
}

n_chains = 20
sigma_ecc_prior_dist = dist.Uniform(0.0, 1.0)
sigma_ecc_prior = sigma_ecc_prior_dist.sample(jrd.PRNGKey(3), (n_chains,))

initial_position = sigma_ecc_prior.reshape(-1, 1)

n_dim = initial_position.shape[1]


n_layers = 10
hidden_size = [512, 512]
num_bins = 10

model = MaskedCouplingRQSpline(n_dim, n_layers, hidden_size, num_bins, jrd.PRNGKey(4))


def model(x, data):
    sigma_ecc = x[..., 0]
    log_prior = sigma_ecc_prior_dist.log_prob(sigma_ecc)

    ecc_model = dist.HalfNormal(**{"scale": sigma_ecc, "validate_args": True})

    integral_individual = jax.tree.map(
        lambda y: jax.scipy.special.logsumexp(ecc_model.log_prob(y[..., 0])) - jnp.log(y.shape[0]),
        data["data"],
    )

    log_likelihood = jnp.sum(jnp.asarray(jax.tree.leaves(integral_individual)))
    log_likelihood = jnp.where(jnp.isnan(log_likelihood), -jnp.inf, log_likelihood)

    return log_likelihood + log_prior


step_size = 1e-1
MALA_Sampler = MALA(model, True, {"step_size": step_size})


n_loop_training = 100
n_loop_production = 100
n_local_steps = 100
n_global_steps = 10
num_epochs = 10

learning_rate = 0.005
momentum = 0.9
batch_size = 5000
max_samples = 5000


rng_key_set = jrd.PRNGKey(5)


nf_sampler = Sampler(
    n_dim,
    rng_key_set,
    jnp.zeros(n_dim),
    MALA_Sampler,
    model,
    n_loop_training=n_loop_training,
    n_loop_production=n_loop_production,
    n_local_steps=n_local_steps,
    n_global_steps=n_global_steps,
    n_chains=n_chains,
    n_epochs=num_epochs,
    learning_rate=learning_rate,
    momentum=momentum,
    batch_size=batch_size,
    use_global=True,
)

nf_sampler.sample(initial_position, data=data)
```

## Note

This example mirrors my actual use case, albeit in a simplified form. Additionally, I've generated an unequal number of random points in the data, which necessitates the use of dictionaries.

**Comment by kazewong** [comment]
The reason is linked to the PR #156 , instead of using params to keep parameters in local sampler, the local sampler parameters are now in the class variable. 

The public doc is not correctly built yet, and thank for noticing me.

To fix this problem, change the line from 
```
MALA_Sampler = MALA(model, True, {"step_size": step_size})
```

to 

```
MALA_Sampler = MALA(model, True, step_size=step_size)
```

**Comment by Qazalbash** [comment]
@kazewong Thanks, it worked!

**Comment by kazewong** [comment]
Update, v0.3.1 should be reasonable now
